# Generated by Django 4.2.2 on 2023-07-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_cat_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cat',
            name='image',
            field=models.CharField(default='', max_length=250),
        ),
    ]
